COMPILER=ifort
OPTIMIZATION=-Ofast

DMC: bec_dmc.o bec_vmc.o io_handler.o DMC.f90
	$(COMPILER) $(OPTIMIZATION)  -qopenmp -llapack io_handler.o bec_dmc.o bec_vmc.o DMC.f90 -o DMC.x 
io_handler.o: io_handler.f90
	$(COMPILER) $(OPTIMIZATION) -qopenmp -c io_handler.f90
bec_dmc.o: bec_vmc.o bec_dmc.f90 
	$(COMPILER) $(OPTIMIZATION) -qopenmp -c bec_dmc.f90	
bec_vmc.o: bec_vmc.f90 
	$(COMPILER) $(OPTIMIZATION) -qopenmp -c bec_vmc.f90
